apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-http-readiness
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        readinessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 4
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            port: 80
        ports:
        - containerPort: 80
        
